version: '3.9'

services:
  alttexter_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: alttexter:latest
    ports:
      - "${ALTTEXTER_PORT}:${ALTTEXTER_PORT}"
    volumes:
      - ${ALTTEXTER_CERTS_DIR}:/certs
    environment:
      - LANGFUSE_TRACING
      - LANGFUSE_PUBLIC_KEY
      - LANGFUSE_SECRET_KEY
      - LANGFUSE_HOST      
      - ALTTEXTER_MODEL
      - OPENAI_API_KEY
      - AZURE_OPENAI_ENDPOINT
      - AZURE_OPENAI_API_KEY
      - AZURE_OPENAI_DEPLOYMENT
      - ALTTEXTER_TOKEN
    command: python main.py --port ${ALTTEXTER_PORT} --host ${ALTTEXTER_HOST} --certfile /certs/${ALTTEXTER_CERTFILE_NAME} --keyfile /certs/${ALTTEXTER_KEYFILE_NAME}